---

- name: Create a Parition
  parted:
          device: /dev/sdb
          number: 1
          part_end: 800MB
          state: present

- name: Create a volume group
  lvg:
          vg: vg_database
          pvs: /dev/sdb1

- name: Create a logical volume
  lvol:
          lv: lv_mysql
          vg: vg_database
          size: 512m

- name: Create an XFS filesystem
  filesystem:
          fstype: xfs
          dev: /dev/vg_database/lv_mysql

- name: Create mount point
  file:
          path: /mnt/mysql_backups
          state: directory

- name: Mount lv_mysql persistently
  mount:
          src: /dev/vg_database/lv_mysql
          path: /mnt/mysql_backups
          fstype: xfs
          state: mounted

- command: partprobe
