---

#ahmed.gaberym@gmail.com
#            If a server has more than 2048MB of RAM, then parameter vm.swappiness is set to 10.
#            If a server has less than 2048MB of RAM, then the following error message is displayed:
#                                   Server memory less than 2048MB

- hosts: all
  become: yes
  tasks:

          - name: configure sysctl
            sysctl:
                    name: vm.swappiness
                    value: 10
                    state: present
            when: ansible_memtotal_mb > 2048
          - debug:
                  msg: "vm.swappiness value is set to 10. Server memory is greater than 2048MB"
            when: ansible_memtotal_mb > 2048


          - debug:
                  msg: "Server memory less than 2048MB"
            when: ansible_memtotal_mb < 2048
